kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    run: nginx-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30062
  type: LoadBalancer
  selector:
     run: nginx-app
